networks:
  enderdragonkiller:

services:
  gateway:
    build: ./gateway
    networks:
      - enderdragonkiller
    ports:
      - 80
    restart: always

  gamebot:
    build: ./gamebot
    deploy:
      replicas: 10
    environment:
      GATEWAY_HOST: gateway
      MCSERVER_HOST: ${MCSERVER_HOST}
      MCSERVER_PORT: ${MCSERVER_PORT}
      MCSERVER_VERSION: ${MCSERVER_VERSION}
    networks:
      - enderdragonkiller
    restart: always
